#dir_file: /home/linusben/Desktop/
dir_file: /Users/Ram/Desktop/
#dir_home: /home/linusben/pubshelf/
dir_home: /Users/Ram/tk320/pubshelf/
dir_db: db.test/
db_name: pubshelf.db
author_name: Taejoon Kwon
apps:
  ## Linux
  #pdf: /usr/bin/acroread
  #html: /usr/bin/firefox

  ## Mac OSX
  pdf: open -a Preview
  html: open -a Firefox
