#home_path: /home/linusben/Desktop/
home_path: /home/linusben/pubshelf.bak/batch/data/
db_path: db/pubshelf.db
file_path: /home/linusben/pubshelf/db/
dbname: Local
apps:
  pdf: /usr/bin/acroread
  html: /usr/bin/firefox
